### ISSUE TITLE
Tambah pekerjaan di perusahaan lain

### ISSUE THREAD

**Issue by budi7** [ThunderID/HR_WEB#100]
- [x]  Dropdown kalender tidak bisa dipilih. sedangkan kalender required.
  ![err](https://cloud.githubusercontent.com/assets/10555410/7962683/e534bf84-0a38-11e5-863e-61b9060382c0.JPG)
- [x] can't store work
  ![err](https://cloud.githubusercontent.com/assets/10555410/7962773/7331dd30-0a39-11e5-87fc-2869da06de32.JPG)

**Comment by budi7** [comment]
#83 #89

**Comment by chelsymooy** [comment]
working on
https://github.com/ThunderID/Work/commit/eff4511eafc88c1d6e5dbb996b4bb504c9abec80
and
https://github.com/ThunderID/Organisation/commit/a2798703c2b897c1ad068f231a0cdee8935ebfa5
