### ISSUE TITLE
UI: Org > Kalender > add

### ISSUE THREAD

**Issue by erickmo** [ThunderID/HR_WEB#103]
![screen shot 2015-06-03 at 9 46 23 pm](https://cloud.githubusercontent.com/assets/3970375/7962859/ff3b7d04-0a39-11e5-9e93-73a433d5f7f5.png)
- [x] Hari kerja dikasih pilihan senin-minggu
- [x] Start -> jam masuk (default)
- [x] End -> jam pulang (default)
- [x] Tombol batal (setelah save salah) kembali ke form terus

**Comment by agilma** [comment]
https://github.com/ThunderID/HR_WEB/commit/aa45ba8ea194b5447ed1021ca7f9ee8e03c2fd0c hari kerja dari senin-minggu
