### ISSUE TITLE
UI: org > Kalender > edit

### ISSUE THREAD

**Issue by erickmo** [ThunderID/HR_WEB#104]
![screen shot 2015-06-03 at 9 51 15 pm](https://cloud.githubusercontent.com/assets/3970375/7962989/b8dac6e8-0a3a-11e5-80c0-0b72dfa6016e.png)
- [x] waktu edit, keluarnya monday-sunday, jadi kalau disave error

**Comment by chelsymooy** [comment]
Permasalahan seeding (belum di ganti dalam bahasa Indonesia)
