### ISSUE TITLE
UI: org.show

### ISSUE THREAD

**Issue by erickmo** [ThunderID/HR_WEB#106]
- [x] Menu di panel header dihilangkan
- [x] Menu di kiri jadi sbb:
- Organisasi 
  - Edit
  - Hapus
- Pengaturan
  - Kalendar Kerja     (+) -> icon pull right, kalau klik di icon buka form
    - Filter 1
    - Filter 2
    - Filter 3  
  - Jenis Cuti             (+) -> icon pull right, kalau klik di icon buka form
    - Filter 1
    - Filter 2
    - Filter 3  
  - Dok. Personalia   (+) -> icon pull right, kalau klik di icon buka form
    - Filter 1
    - Filter 2
    - Filter 3  
- Data
  - Cabang                (+) -> icon pull right, kalau klik di icon buka form
  - Karyawan

**Comment by agilma** [comment]
yang filter tetap saya taruh dibawah pak, karena kalau kebayakan filter user harus scroll lagi kebawah kalau ingin buka menu dibawah.
