### ISSUE TITLE
return value date not null

### ISSUE THREAD

**Issue by budi7** [ThunderID/HR_WEB#35]
![error3](https://cloud.githubusercontent.com/assets/10555410/7335966/9b002baa-ec0c-11e4-9c03-269e5426987e.JPG)

**Comment by agilma** [comment]
masih simpan zero date jika edit karir pekerjaan dikosongkan 
![screen shot 2015-04-27 at 11 07 16 am](https://cloud.githubusercontent.com/assets/4099329/7341519/b68d875c-eccd-11e4-8c7d-42fbaadb47d5.png)

ini hasil simpan ke database
![screen shot 2015-04-27 at 11 07 42 am](https://cloud.githubusercontent.com/assets/4099329/7341520/b8e8fbee-eccd-11e4-9942-ff58e140254b.png)

jadi ke baca zero date di tampilannya
![screen shot 2015-04-27 at 11 10 22 am](https://cloud.githubusercontent.com/assets/4099329/7341534/0fb5fae4-ecce-11e4-9034-bf4382285df8.png)

**Comment by chelsymooy** [comment]
Please
