### ISSUE TITLE
pesan error aneh

### ISSUE THREAD

**Issue by budi7** [ThunderID/HR_WEB#36]
![error4](https://cloud.githubusercontent.com/assets/10555410/7335970/ba500cb4-ec0c-11e4-89a7-eef7f4c8efbe.JPG)

**Comment by budi7** [comment]
hapus branch

**Comment by chelsymooy** [comment]
anehnya gimana? perusahaan yang punya chart tidak bisa dihapus

**Comment by budi7** [comment]
my bad
