### ISSUE TITLE
Waktu create person baru

### ISSUE THREAD

**Issue by chelsymooy** [ThunderID/HR_WEB#39]
- waktu create baru button tambah untuk tiap menu (kontak, kerabat) tidak ada
- error waktu karyawan baru di create 

![error 1](https://cloud.githubusercontent.com/assets/5895063/7340535/ed342a54-ecb9-11e4-93cb-e204bdb66992.png)

**Comment by budi7** [comment]
[waktu create baru button tambah untuk tiap menu (kontak, kerabat) tidak ada] 
maksudnya piye chel? 
kan kmrn memang dihilangkan (issue #30)

**Comment by budi7** [comment]
[error waktu karyawan baru di create] 
erronya pas ngapain ya chel? kok di saya & mas Agil ga ada masalah yaa
![erorr1](https://cloud.githubusercontent.com/assets/10555410/7340869/3002a93a-ecc1-11e4-8f67-3093aa5a6173.JPG)

**Comment by chelsymooy** [comment]
Coba create kryawan baru.

**Comment by chelsymooy** [comment]
Pilih mnu kryawan trus create baru. Save, terus show kryawan yg baru itu
