### ISSUE TITLE
Miscellaneous

### ISSUE THREAD

**Issue by chelsymooy** [ThunderID/HR_WEB#44]
- [x] Semua button batal pada form dibuat redirect ke last page.
- [x] Semua update weak entity dibuat redirect ke show
- [x] Tanggal lahir dibuat batasan (sampai sekarang)

**Comment by agilma** [comment]
untuk yg tanggal lebih baik dibwt di controller karna jquery utk inputmask msh belum bisa menghandle, karna bakal ada di updatean terbaru inputmask yg versi 3.4
