### ISSUE TITLE
API for fp

### ISSUE THREAD

**Issue by budi7** [ThunderID/HR_WEB#55]
- [x] api for enroll new finger from registered employee.
- [x] api for update

**Comment by chelsymooy** [comment]
'api for delete registered finger from registered employee'

In what cases it is might be needed?

**Comment by chelsymooy** [comment]
what are terms of update api ?

Scheme for now on : 
- send local databases 
- sync in web
- send updated databases (local removed)

**Comment by chelsymooy** [comment]
- sync finger api provided
