### ISSUE TITLE
Create Work

### ISSUE THREAD

**Issue by chelsymooy** [ThunderID/HR_WEB#56]
- [x] Waktu posisi di ganti ada pilihan calendar berdasarkan posisi (route ajax : follow line 644)

**Comment by agilma** [comment]
respon dari ajax controllernya msh angka, blm dpt nama dari schedulenya.

**Comment by agilma** [comment]
ada bugs di person work, wktu add works

![screenshot from 2015-05-21 14 30 07](https://cloud.githubusercontent.com/assets/4099329/7743576/57d57042-ffc6-11e4-8b87-1d8a6c0e4c87.png)

hasilnya ttp seperti ini

![screenshot from 2015-05-21 14 28 37](https://cloud.githubusercontent.com/assets/4099329/7743579/5f89072c-ffc6-11e4-9f58-bb5537112770.png)

tapi di DB masuk datanya.

![screenshot from 2015-05-21 14 34 24](https://cloud.githubusercontent.com/assets/4099329/7743597/8f8326d8-ffc6-11e4-8dc2-a590ef7678c1.png)

**Comment by chelsymooy** [comment]
datanya yang mana ?

**Comment by chelsymooy** [comment]
Kalau ada reason end job dianggap masuk pengalaman (tidak ditampilkan di profil melainkan di works).
Profil menampilkan pekerjaan saat ini

**Comment by agilma** [comment]
ini ada bugs di add work, disaat karyawan gak ada pekerjaan, masukin 1 pekerjaan jd yg muncul bnyk pekerjaan tp di urutan terakhir yg dmasukkan td muncul

![screenshot from 2015-05-22 10 18 24](https://cloud.githubusercontent.com/assets/4099329/7763559/df1bef8a-006c-11e5-81cf-4e8684692646.png)

![screenshot from 2015-05-22 10 21 57](https://cloud.githubusercontent.com/assets/4099329/7763558/de7fe798-006c-11e5-9b86-7dd5f5c5a9de.png)
