### ISSUE TITLE
Test Deadlock

### ISSUE THREAD

**Issue by chelsymooy** [ThunderID/HR_WEB#80]
- Jadikan satu PC sebagai server
- [x] Running 50 process random (tracker/fp) setting pada saat bersamaan dengan jumlah record paling sedikit 200 lines.
- Notes : test melalui terminal untuk 2 request, salah satunya harus menunggu yang satu selesai
  cc : @uchuy77

**Comment by budi7** [comment]
tested w/ 3 computer running 400lines
