### ISSUE TITLE
Functionality Error

### ISSUE THREAD

**Issue by budi7** [ThunderID/HR_WEB#89]
# Data Karyawan
## Tambah Karyawan
#83 Data Karyawan - tambah karyawan
- [x] field unique id sudah di isi tapi statusnya masih belum di-isi
  ![err](https://cloud.githubusercontent.com/assets/10555410/7909335/9bab8790-0875-11e5-9d68-b841aed6a195.JPG)
#83 Data Relative (relationship, check organisation active) - lihat relasi
- [x]  [question] data relasi bisa berbeda satu dengan yang lain. pada data relasi A, B adalah pasangan. Namun, pada data B, tidak ada data A, namun data C sebagai orang tua.
  ![err](https://cloud.githubusercontent.com/assets/10555410/7909840/9085d1a0-0879-11e5-878e-e2e5ec5ad8eb.JPG)
  ![err1](https://cloud.githubusercontent.com/assets/10555410/7909841/9086adbe-0879-11e5-9040-a576cd6ea80c.JPG)

---
## Tambah Karyawan

 #83 Data Pekerjaan 
- [x] pekerjaan berubah setelah punya end job date
- jabatannya staff 
  ![err](https://cloud.githubusercontent.com/assets/10555410/7910308/c36cf388-087d-11e5-804c-8dfa3381634a.JPG)
1. lalu dipromosikan jadi CEO -> edit posisi jadi CEO di Malang
   ![err1](https://cloud.githubusercontent.com/assets/10555410/7910275/7d004742-087d-11e5-9058-2f422dc290db.png)
2. setelah punya end date, berubah jadi staff dan bukan ceo
   ![err3](https://cloud.githubusercontent.com/assets/10555410/7910279/8305ea8e-087d-11e5-98e7-ba913999a216.JPG)

---
## Data Cuti

 #83 Data Cuti (Cek pas pengajuan cuti, jika quotanya tidak cukup apa bisa mengajukan cuti)
- [x] jatah absennya 15 hari, tapi bisa pilih start to end 1 bulan
  ![err](https://cloud.githubusercontent.com/assets/10555410/7910416/9dcbd81e-087e-11e5-9d58-6a38764b4d5c.JPG)
  keterangan  
  1 : hak cuti checked
  2 : hak cuti unchecked
- [x] [question] cuti 1 tahun ?
  ![err](https://cloud.githubusercontent.com/assets/10555410/7910587/4a711e16-0880-11e5-9e5d-4e50a3aaaf16.JPG)

---
## Data Contact
#83 Data contact
- [x] menambahkan email => error
  ![err](https://cloud.githubusercontent.com/assets/10555410/7936512/d4e0ca54-0963-11e5-894c-6f8a4ee05a6e.JPG)

**Comment by chelsymooy** [comment]
Cuti satu tahu : itu jatah cuti, bukan pengajuan cuti berlaku dari start sampai end, pengajuan cuti di person schedule . Ada usul buat caption yg bgs biar tdk salah paham?

**Comment by chelsymooy** [comment]
Catatan. History pekerjaan tdk boleh berubah posisi. Cuma bisa tambah end date. Kalau berubah status harus menambah posisi baru. Nnti q tambahkan error msg ny. @uchuy77 tlong tmbahkan dlm manual book

**Comment by chelsymooy** [comment]
Untuk relative hubungan nya milik karyawan, nanti di tambahkan status : relasi dari **
