### ISSUE TITLE
UI: Settings > Organisasi

### ISSUE THREAD

**Issue by erickmo** [ThunderID/HR_WEB#96]
![screen shot 2015-06-03 at 9 26 42 pm](https://cloud.githubusercontent.com/assets/3970375/7962387/4846dd0c-0a37-11e5-9db4-44eeea4e493d.png)
- [x] Karena tampilan terlalu plain dan supaya seragam sama tampilan yang lain, sebaiknya di sebelah kiri dikasih filter seperti di personalia - Isinya cuman "semua organisasi" (untuk kedepannya bisa kita tweak lagi)
- [x] Untuk daftar organisasi supaya tidak terlalu plain, mungkin bisa ditambahkan info seperti jumlah kantor, jumlah karyawan
- [x] Untuk tombol edit & trash, mungkin diberi border bulatan supaya lebih clear kalau itu tombol. Tolong diapply ke semua tombol edit & delete

**Comment by budi7** [comment]
need help @chelsymooy

**Comment by budi7** [comment]
tolong dicek knp jumlahnya sama (kata Mas Agil) @chelsymooy 
![err](https://cloud.githubusercontent.com/assets/10555410/7983359/b556ee2a-0ae9-11e5-8fc1-0dd9a297aed9.JPG)
![as](https://cloud.githubusercontent.com/assets/10555410/7983364/c3c68f24-0ae9-11e5-8420-d49c431422d6.JPG)

**Comment by chelsymooy** [comment]
https://github.com/ThunderID/HR_WEB/commit/a2bda4c649e38e7ca422ff08f85b1ba8eb7cd645
