### ISSUE TITLE
UI: Penambahan organisasi

### ISSUE THREAD

**Issue by erickmo** [ThunderID/HR_WEB#97]
![screen shot 2015-06-03 at 9 29 00 pm](https://cloud.githubusercontent.com/assets/3970375/7962506/e336d3c6-0a37-11e5-83af-ba9679aa7749.png)
- [x] error & nama field tidak sama. Di form "Nama Organisasi", di error "name"

**Comment by chelsymooy** [comment]
Fixed https://github.com/ThunderID/Organisation/commit/a2798703c2b897c1ad068f231a0cdee8935ebfa5
